### ISSUE TITLE
Requesting permission to use some part of your scripts

### ISSUE THREAD

**Issue by GaelKBertrand** [esagiev/Multi-Agent_Reinforcement_Learning#2]
Hi Prof. @esagiev , I am completing a small report on Policy Hill Climbing combined with the Wolf principle. I would like to ask if I can pick some parts of your python scripts and modify them to demonstrate some specific results. I am asking because there is no specific licenses on this repo. 

Thanks!

**Comment by esagiev** [comment]
Hi Gael. Sure, you can use it. I hope it will help you somehow.
